fix exception:
org.eclipse.core.internal.resources.ResourceException: Resource '/earprj/WebContent/WEB-INF/classes/META-INF' does not exist.
     [java] 	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:317)
     [java] 	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:194)
     [java] 	at org.eclipse.core.internal.resources.Container.members(Container.java:181)
     [java] 	at org.eclipse.core.internal.resources.Container.members(Container.java:164)
     [java] 	at org.jboss.tools.common.model.filesystems.impl.FolderImpl.getResources(FolderImpl.java:951)
     [java] 	at org.jboss.tools.common.model.filesystems.impl.FolderImpl.loadChildren(FolderImpl.java:128)
     [java] 	at org.jboss.tools.common.model.impl.RegularObjectImpl.getChildren(RegularObjectImpl.java:56)
     [java] 	at org.jboss.tools.jst.web.tld.TaglibMapping.findTldsInFolder(TaglibMapping.java:215)
     [java] 	at org.jboss.tools.jst.web.tld.TaglibMapping.findTldsInFolder(TaglibMapping.java:219)
     [java] 	at org.jboss.tools.jst.web.tld.TaglibMapping.findTldsInFolder(TaglibMapping.java:219)
     [java] 	at org.jboss.tools.jst.web.tld.TaglibMapping.loadTldsInWebInf(TaglibMapping.java:172)
     [java] 	at org.jboss.tools.jst.web.tld.TaglibMapping.revalidate(TaglibMapping.java:82)
     [java] 	at org.jboss.tools.jsf.web.JSFWatcherContributor.updateProject(JSFWatcherContributor.java:49)
     [java] 	at org.jboss.tools.common.model.project.Watcher.updateAll(Watcher.java:109)
     [java] 	at org.jboss.tools.common.model.project.Watcher.access$0(Watcher.java:92)
     [java] 	at org.jboss.tools.common.model.project.Watcher$WatcherRunnable.run(Watcher.java:52)
     [java] 	at org.jboss.tools.common.model.XJob.run(XJob.java:119)
     [java] 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


git-svn-id: http://svn.jboss.org/repos/jbosstools/trunk@9613 a97e2381-89e5-4abb-bab3-167db6db766c